#!/bin/bash

cat << heredoc
{
Tutorial: Inspeção aos quadros elétricos (manutenção preventiva)

Texto escrito de forma a ser interpretado por script, mais info no fundo do documento

Foto "antes": quadro sem máscaras
Foto "depois": quadro ja com máscaras
}

Aperto dos terminais

Nome do quadro: (encontra-se escrito na OT)
Duração:
Data:

• Tem portas?
[  ] Sim
[  ] Não

• As portas estão afinadas?
[  ] Sim
[  ] Não

• As portas estão danificadas/partidas?
[  ] Não
[  ] Sim

• Fechaduras OK?
[  ] Sim
[  ] Não

• Dobradiças OK?
[  ] Sim
[  ] Não

• Manipulos de tampas partidos?
[  ] Não
[  ] Sim

• Tem parafusos partidos ou não enroscam nas máscaras?
[  ] Não
[  ] Sim
[  ] Faltam parafusos (precisa revisão)

• Tem disjuntores partidos?
[  ] Não
[  ] Sim

• Existem diagramas elétricos?
[  ] Sim
[  ] Sim, riscados
[  ] Sim, danificados
[  ] Sim, ainda não foram lidos para verificação
[  ] Não

• Os circuitos estão bem identificados?
{Quadros elétricos pintados a caneta é vandalismo}
[  ] Sim
[  ] Tem anotações a caneta, lápis ou pinturas
[  ] Tem Identificações descoladas ou quase a descolar
[  ] Não tem diagramas eletricos

• Tem fitas de papel em vez de fita isoladora?
[  ] Não tem fitas de papel
[  ] Tem fitas de papel para apertar cabos em vez de braçadeiras de serrilha {proibido}
[  ] Tem fitas de papel a identificar disjuntores


• Luzes sinalizadoras OK?
[  ] Sim
[  ] Não sinalizam correto
[  ] Não estão montados sinalizadores

• Existem fios terra (PE) desde as portas metalicas até ao QE?
[  ] Sim
[  ] Não
[  ] N/A (Não aplicável)
[  ] As portas não são metalicas (desnecessário)

• As portas do QE tem a identificação correta do seu nome?
[  ] Sim
[  ] Não, está incorreta
[  ] Não tem quaisquer identificações

• O quadro contém objetos estranhos no interior?
[  ] Não
[  ] Sim

• Ventiladores precisam de manutenção?
[  ] Não
[  ] Sim
[  ] O quadro não foi construido com ventilação

• Tem borrachas de isolamento nas portas?
[  ] Sim
[  ] Estão danificadas
[  ] O modelo das portas não faz uso de borrachas

• Os diferenciais foram testados?
{alguns devem ser testados mensalmente}
[  ] Não testado, motivos de horário desadequado

• Tem materiais em falta?
[  ] Não
[  ] Sim, tampas de calha técnica
[  ] Sim, faltam máscaras de proteção nos espelhos
[  ] Sim, falta de espelhos
[  ] Sim, falta de faces externas ao quadro (desprotegido)

• Todos os parafusos foram reapertados?
{Com chaves isoladas, Começando pelos bornes Vicking; Apertar tudo tudo tudo)
[  ] Sim, com chaves isoladas
[  ] Não totalmente
[  ] Não

• Foi aplicado dieletrico?
{Lavar Sempre com Tensol num borrifador seco e sem residuos de água. Os cabos tem de ficar todos brilhantes}
[  ] Sim, os contactos foram borrifado tensol
[  ] Não totalmente
[  ] Não

• Por cima do quadro existem bocins danificados/inexistentes ou existem buracos no quadro elétrico?
{às vezes repara-se com cola-quente}
[  ] Não
[  ] Sim

• Os espelhos foram limpos por dentro com pano seco?
{Para ser eficiente: Retirar por ordem. De preferencia de baixo para cima para que no chão fiquem igualmente empilhadas de baixo para cima}
[  ] Sim
[  ] Não

• Os espelhos foram limpos por fora?
[  ] Sim, com tensol
[  ] Não totalmente
[  ] Não
{Com um pano seco, remover excesso de tensol. Evitar água e sabão mesmo da parte de fora do quadro}

• O quadro foi soprado?
{Usar extensão se necessário}
[  ] Sim
[  ] Não

• As faces externas do QE foram limpas?
[  ] Sim, com tensol
[  ] Não totalmente
[  ] Não
{Verificar arestas externas ao quadro após passar pano seco, tensol e novamente pano seco. O quando deve estar tão limpo por dentro quanto por fora}

• Os barramentos foram apertados?
{Para apertar barramentos pode ser preciso chaves allen. É feito fora do horario normal. Necessário sempre 2 pessoas no minimo}
[  ] Sim
[  ] Não

• Leituras
L1:
L2:
L2:
N:

_______________________________________
Materiais possivelmente necessários:
- Escadote
- Soprador
- Extensão eletrica (para ligar soprador)
- Tensol
- Panos secos
- Head Light
- Pinça Amperimetrica pra leituras
...


Para converter este ficheiro de texto (origem na app: "Samsung Notes") para texto simples puramente legivel (sem necessidade de intrepretar e sem quadriculas de "Sim" + "Não" no formato "Checklist") é favor exportar para "texto.txt" para a pasta "raiz/upK/intermedTexto" no smarthphone e de seguida utilizar a app "upK" escrita em linguagem de programação "bash" e que é acessivel pela app "Termux" presente no smartphone do Mike 1 e do colaborador David Rodrigues. No entanto a app ainda está em desenvolvimento (a app também poderá converter o texto para markdown)

Info
- O conteúdo de parenteses {} será apagado pela aplicação
- Duplos parenteses retos indicam que é possivel que toda a frase seja apagada caso a Check Box do inicio da frase seja assinalada


Info: Saniclean é uma espuma de limpeza mas é mais cara

}




heredoc
