#+TITLE: upk website
#+DESCRIPTION: from org-mode export to website
#+EXPORT_FILE_NAME: ./website/exported-website-from-emacs/index.html
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup

* upK info
*** Facilities up-keeping
- Script for UPK maintenance aid
- This github repository is OPEN SOURCE despite the fact upK is private company. It means that anybody can contribute to this repository if they produce content TO HELP this project and this company in some positeve way.
- If you are a foreigner to upK and you still want to contribute with your pull requests, you can for example feed into the repository any info about "Cascais Shopping" (for example) in order to help the employees to navigate the terrain better.
- This repo has 2 branches permanently under construction: main and gh-pages. The first id the branch to run inside Termux app. The second one is a secondary website for upK.

* info about this repository
*** CS folder/directory
The content of the CS directory is dedicated to "Cascais Shopping" client. Inside you can finde some activities, scripts and employee aid

* Services available by upK (written in Pt-Pt)
- AVAC
- Eletricidade
- Mecânica
- Segurança e Vigilância
- Construção Civil
- Instrumentação
- Serralharia
- Soldadura
- Canalizações
- Hidraulica
- Piping aço e poliester
- Limpeza e desobstrução de tubagens

* About home.bashrc file
It is a file that copies ~/.bashrc but it is named home.bashrc in order not to be hidden from new Linux/Bash users

* Github Source code
https://github.com/SeivaDArve/upK

* Installing DRYa (for custom filesystem navigation)
https://github.com/SeivaDArve/DRYa.git

* Sincronizar todo o conteúdo da UPK
Existe info da UPK nos seguintes locais:
- Dropbox (mydvr7@gmail.com)
- Samsung Galaxy A6+ (David Rodrigues)
- Termux (David Rodrigues)
- Termux (Mike 1)
- Pen USB (David rodrigues)
- Youtube (mydvr7)
- HDD (David Rodrigues)
- Samsung notes (David Rodrigues)

* For next version
  # List of what is lacking at this version to transcend to the next version:
  1. contar-Horas-Semanais-Automaticamente.el (pra verificarboletim)
  2. alegoritmo-Inspec-QEs.sh (app the aplica no ecra SO UMA ETAPA DE CADA VEZ para nao ser demasiada informacao)
  3. botaoHoras-Entrada-Saida.sh (este botao é para ser clicado no ato da assinar para entrada no shopping e para saida no shopping, para que registe a hora certa escrita no papel vo Vitor15)
  4. add "git pull" at .bashrc with a timer of 5 seconds to allow the user to cancel
