#+TITLE: Tipos de OTs no SIIGO (com abreviaturas)
#+STARTUP: indent

(Pode [[elisp:(progn (kill-buffer) (delete-window))][fechar]] esta página, pode [[elisp:(funcall-interactive 'read-only-mode)][editar]], ou pode ver as [[Instruções][instruções]] no fundo)

--- AVAC -----------------------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(gt) Comando de iluminação/AVAC através da GTC  - Técnico")(other-window -1)(kill-buffer)(delete-window))][gt]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(gt) Comando de iluminação/AVAC através da GTC  - Técnico")(other-window -1)(kill-buffer)(delete-window))][Comando de iluminação/AVAC através da GTC  - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(0) Intervenções em VCs das lojas - piso 0 - Técnico")(other-window -1)(kill-buffer)(delete-window))][0]])        > [[elisp:(progn (other-window 1)(end-of-line)(insert "(0) Intervenções em VCs das lojas - piso 0 - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções em VCs das lojas - piso 0 - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(1) Intervenções em VCs das lojas - piso 1 - Técnico")(other-window -1)(kill-buffer)(delete-window))][1]])        > [[elisp:(progn (other-window 1)(end-of-line)(insert "(1) Intervenções em VCs das lojas - piso 1 - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções em VCs das lojas - piso 1 - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(s de av) Trabalhos diversos de AVAC - Técnico")(other-window -1)(kill-buffer)(delete-window))][s de av]])  > [[elisp:(progn (other-window 1)(end-of-line)(insert "(s de av) Trabalhos diversos de AVAC - Técnico")(other-window -1)(kill-buffer)(delete-window))][Trabalhos diversos de AVAC - Técnico]]


--- Acompanhamentos, Testes & Contagens -----------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(os ex) Apoio a empreiteiros exteriores")(other-window -1)(kill-buffer)(delete-window))][os ex]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "(os ex) Apoio a empreiteiros exteriores")(other-window -1)(kill-buffer)(delete-window))][Apoio a empreiteiros exteriores]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(as ex) Apoio de empresas exteriores")(other-window -1)(kill-buffer)(delete-window))][e em]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(as ex) Apoio de empresas exteriores")(other-window -1)(kill-buffer)(delete-window))][Apoio de empresas exteriores]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(fl) Contagem de Energia e Fluidos - Técnico")(other-window -1)(kill-buffer)(delete-window))][fl]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(fl) Contagem de Energia e Fluidos - Técnico")(other-window -1)(kill-buffer)(delete-window))][Contagem de Energia e Fluidos - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(a em L) Contagem de energia em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][a em L]])   > [[elisp:(progn (other-window 1)(end-of-line)(insert "(a em L) Contagem de energia em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Contagem de energia em lojas - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(che) Verificação de cheiros (gás, esgotos, etc) - Produto")(other-window -1)(kill-buffer)(delete-window))][che]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(che) Verificação de cheiros (gás, esgotos, etc) - Produto")(other-window -1)(kill-buffer)(delete-window))][Verificação de cheiros (gás, esgotos, etc) - Produto]]

--- Apoio ao Marketing ---------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(temp) Apoio a stands temporários - Produto")(other-window -1)(kill-buffer)(delete-window))][temp]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(temp) Apoio a stands temporários - Produto")(other-window -1)(kill-buffer)(delete-window))][Apoio a stands temporários - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(mar) Apoio ao Marketing/Eventos - Produto")(other-window -1)(kill-buffer)(delete-window))][mar]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(mar) Apoio ao Marketing/Eventos - Produto")(other-window -1)(kill-buffer)(delete-window))][Apoio ao Marketing/Eventos - Produto]]

--- Construção Civil -----------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(calc) Reparação/Substituição de pedras da calçada - Produto")(other-window -1)(kill-buffer)(delete-window))][calc]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(calc) Reparação/Substituição de pedras da calçada - Produto")(other-window -1)(kill-buffer)(delete-window))][Reparação/Substituição de pedras da calçada - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(pin) Trabalhos de pintura no centro e parques - Produto")(other-window -1)(kill-buffer)(delete-window))][pin]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(pin) Trabalhos de pintura no centro e parques - Produto")(other-window -1)(kill-buffer)(delete-window))][Trabalhos de pintura no centro e parques - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(cons) Trabalhos diversos de construção civil - Produto")(other-window -1)(kill-buffer)(delete-window))][cons]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(cons) Trabalhos diversos de construção civil - Produto")(other-window -1)(kill-buffer)(delete-window))][Trabalhos diversos de construção civil - Produto]]

--- Electricidade ---------------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(bl) Intervenções em blocos autónomos - Técnico")(other-window -1)(kill-buffer)(delete-window))][bl]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(bl) Intervenções em blocos autónomos - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções em blocos autónomos - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(lig) Ligar/Desligar Iluminação Exterior - Técnico")(other-window -1)(kill-buffer)(delete-window))][lig]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(lig) Ligar/Desligar Iluminação Exterior - Técnico")(other-window -1)(kill-buffer)(delete-window))][Ligar/Desligar Iluminação Exterior - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(os em l) Pequenos trabalhos eléctricos em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][os em l]])  > [[elisp:(progn (other-window 1)(end-of-line)(insert "(os em l) Pequenos trabalhos eléctricos em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Pequenos trabalhos electricos em lojas - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(atm) Rearme e pequenos trabalhos em ATM - Produto")(other-window -1)(kill-buffer)(delete-window))][atm]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(atm) Rearme e pequenos trabalhos em ATM - Produto")(other-window -1)(kill-buffer)(delete-window))][Rearme e pequenos trabalhos em ATM - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(es - c) Rearme/Desarme de disjuntores - Centro e Parques - Técnico")(other-window -1)(kill-buffer)(delete-window))][es - c]])   > [[elisp:(progn (other-window 1)(end-of-line)(insert "(es - c) Rearme/Desarme de disjuntores - Centro e Parques - Técnico")(other-window -1)(kill-buffer)(delete-window))][Rearme/Desarme de disjuntores - Centro e Parques - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(res e) Rearme/Desarme de disjuntores em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][res e]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "(res e) Rearme/Desarme de disjuntores em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Rearme/Desarme de disjuntores em lojas - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(of) Reparações eléctricas em oficina - Técnico")(other-window -1)(kill-buffer)(delete-window))][of]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(of) Reparações eléctricas em oficina - Técnico")(other-window -1)(kill-buffer)(delete-window))][Reparações electricas em oficina - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(eme) Subst. Lâmpadas/Outros Trab - Ilum. Emergência - Produto")(other-window -1)(kill-buffer)(delete-window))][eme]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(eme) Subst. Lâmpadas/Outros Trab - Ilum. Emergência - Produto")(other-window -1)(kill-buffer)(delete-window))][Subst. Lâmpadas/Outros Trab - Ilum. Emergência - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(nor) Subst. Lâmpadas/Outros Trab - Ilum. Normal - Produto")(other-window -1)(kill-buffer)(delete-window))][nor]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(nor) Subst. Lâmpadas/Outros Trab - Ilum. Normal - Produto")(other-window -1)(kill-buffer)(delete-window))][Subst. Lâmpadas/Outros Trab - Ilum. Normal - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(os no) Trabalhos eléctricos no centro e parques - Técnico")(other-window -1)(kill-buffer)(delete-window))][os no]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "(os no) Trabalhos eléctricos no centro e parques - Técnico")(other-window -1)(kill-buffer)(delete-window))][Trabalhos electricos no centro e parques - Técnico]]

--- Gás ------------------------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(gas e) Fecho/abertura de gás em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][gas e]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "(gas e) Fecho/abertura de gás em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Fecho/abertura de gás em lojas - Técnico]]

--- Infiltrações ---------------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(oes em l) Infiltrações em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][oes em l]]) > [[elisp:(progn (other-window 1)(end-of-line)(insert "(oes em l) Infiltrações em lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Infiltrações em lojas - Técnico]]

--- Meios Eletromecânicos de Transporte ----------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(vad) Intervenções Várias - Elevadores - Produto")(other-window -1)(kill-buffer)(delete-window))][vad]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(vad) Intervenções Várias - Elevadores - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções Várias - Elevadores - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(tap) Intervenções Várias - Escadas/Tapetes - Produto")(other-window -1)(kill-buffer)(delete-window))][tap]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(tap) Intervenções Várias - Escadas/Tapetes - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções Várias - Escadas/Tapetes - Produto]]

--- Outros ---------------------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(sh) Intervenções em Shop Spots - Produto")(other-window -1)(kill-buffer)(delete-window))][sh]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(sh) Intervenções em Shop Spots - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções em Shop Spots - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(ins) Intervenções várias - Instalações Sanitárias - Produto")(other-window -1)(kill-buffer)(delete-window))][ins]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(ins) Intervenções várias - Instalações Sanitárias - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções várias - Instalações Sanitárias - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(exti) Intervenções várias em equipamentos de extinção de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][exti]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(exti) Intervenções várias em equipamentos de extinção de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções várias em equipamentos de extinção de incêndios - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(za d) Limpeza de áreas Técnicas - Técnico")(other-window -1)(kill-buffer)(delete-window))][za d]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(za d) Limpeza de áreas Técnicas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Limpeza de áreas Técnicas - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(loji) Outro Tipo de Apoio a Lojistas - Técnico")(other-window -1)(kill-buffer)(delete-window))][loji]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(loji) Outro Tipo de Apoio a Lojistas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Outro Tipo de Apoio a Lojistas - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(reu) Preparação trabalhos, reuniões de manutenção, etc - Técnico")(other-window -1)(kill-buffer)(delete-window))][reu]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(reu) Preparação trabalhos, reuniões de manutenção, etc - Técnico")(other-window -1)(kill-buffer)(delete-window))][Preparação trabalhos, reuniões de manutenção, etc - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(vig) Reparações de equipamentos da Segurança/Vigilância - Técnico")(other-window -1)(kill-buffer)(delete-window))][vig]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(vig) Reparações de equipamentos da Segurança/Vigilância - Técnico")(other-window -1)(kill-buffer)(delete-window))][Reparações de equipamentos da Segurança/Vigilância - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(resi) Reparações de equipamentos de tratamento de resíduos")(other-window -1)(kill-buffer)(delete-window))][resi]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(resi) Reparações de equipamentos de tratamento de resíduos")(other-window -1)(kill-buffer)(delete-window))][Reparações de equipamentos de tratamento de resíduos]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(ser) Trabalhos de Serralharia - Técnico")(other-window -1)(kill-buffer)(delete-window))][ser]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(ser) Trabalhos de Serralharia - Técnico")(other-window -1)(kill-buffer)(delete-window))][Trabalhos de Serralharia - Técnico]]

--- Parque de Estacionamento ---------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(oes no) Infiltrações no Centro/Parque - Técnico")(other-window -1)(kill-buffer)(delete-window))][oes no]])   > [[elisp:(progn (other-window 1)(end-of-line)(insert "(oes no) Infiltrações no Centro/Parque - Técnico")(other-window -1)(kill-buffer)(delete-window))][Infiltrações no Centro/Parque - Técnico]]

--- Portas e Portões -----------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(tica) Intervenções em portas automáticas - Produto")(other-window -1)(kill-buffer)(delete-window))][tica]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(tica) Intervenções em portas automáticas - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções em portas automáticas - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(cort) Intervenções em portas corta-fogo - Técnico")(other-window -1)(kill-buffer)(delete-window))][cort]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(cort) Intervenções em portas corta-fogo - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções em portas corta-fogo - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(alu) Intervenções em portas de aluminio e de vidro entrada - Produto")(other-window -1)(kill-buffer)(delete-window))][alu]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(alu) Intervenções em portas de aluminio e de vidro entrada - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções em portas de aluminio e de vidro entrada - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(ger) Intervenções em portas gerais - Produto")(other-window -1)(kill-buffer)(delete-window))][ger]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(ger) Intervenções em portas gerais - Produto")(other-window -1)(kill-buffer)(delete-window))][Intervenções em portas gerais - Produto]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(vai) Intervenções em portas vai-vem - Técnico")(other-window -1)(kill-buffer)(delete-window))][vai]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(vai) Intervenções em portas vai-vem - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções em portas vai-vem - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(gr) Intervenções em portas/gradeamentos das lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][gr]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(gr) Intervenções em portas/gradeamentos das lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções em portas/gradeamentos das lojas - Técnico]]

--- Transporte de Materiais Diversos -------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(ais d) Transporte de Materiais Diversos")(other-window -1)(kill-buffer)(delete-window))][ais d]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "(ais d) Transporte de Materiais Diversos")(other-window -1)(kill-buffer)(delete-window))][Transporte de Materiais Diversos]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(pl) Transporte de plataformas elevatórias")(other-window -1)(kill-buffer)(delete-window))][pl]])       > [[elisp:(progn (other-window 1)(end-of-line)(insert "(pl) Transporte de plataformas elevatórias")(other-window -1)(kill-buffer)(delete-window))][Transporte de plataformas elevatórias]]

--- Aguas ----------------------------------------------------------------------
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(valv) Abertura/Fecho de válvulas da rede de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][valv]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(valv) Abertura/Fecho de válvulas da rede de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][Abertura/Fecho de válvulas da rede de incêndios - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(ho de a) Abertura/Fecho de água  - Técnico")(other-window -1)(kill-buffer)(delete-window))][ho de a]])  > [[elisp:(progn (other-window 1)(end-of-line)(insert "(ho de a) Abertura/Fecho de água  - Técnico")(other-window -1)(kill-buffer)(delete-window))][Abertura/Fecho de água  - Técnico ]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(tanq) Desentupimento de tanques dos corredores técnicos - Técnico")(other-window -1)(kill-buffer)(delete-window))][tanq]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(tanq) Desentupimento de tanques dos corredores técnicos - Técnico")(other-window -1)(kill-buffer)(delete-window))][Desentupimento de tanques dos corredores técnicos - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(dom) Intervenções na bombagem de esgotos domésticos - Técnico")(other-window -1)(kill-buffer)(delete-window))][dom]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(dom) Intervenções na bombagem de esgotos domésticos - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na bombagem de esgotos domésticos - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(plu) Intervenções na bombagem de esgotos pluviais - Técnico")(other-window -1)(kill-buffer)(delete-window))][plu]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(plu) Intervenções na bombagem de esgotos pluviais - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na bombagem de esgotos pluviais - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(reg) Intervenções na central de bombagem-Rede de água da rega - Técnico")(other-window -1)(kill-buffer)(delete-window))][reg]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(reg) Intervenções na central de bombagem-Rede de água da rega - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na central de bombagem-Rede de água da rega - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(a de av) Intervenções na central de bombagem-Rede de água de avac - Técnico")(other-window -1)(kill-buffer)(delete-window))][a de av]])  > [[elisp:(progn (other-window 1)(end-of-line)(insert "(a de av) Intervenções na central de bombagem-Rede de água de avac - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na central de bombagem-Rede de água de avac - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(a de i) Intervenções na central de bombagem-Rede de água de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][a de i]])   > [[elisp:(progn (other-window 1)(end-of-line)(insert "(a de i) Intervenções na central de bombagem-Rede de água de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na central de bombagem-Rede de água de incêndios - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(pota) Intervenções na central de bombagem-Rede de água potável - Técnico")(other-window -1)(kill-buffer)(delete-window))][pota]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(pota) Intervenções na central de bombagem-Rede de água potável - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na central de bombagem-Rede de água potável - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(spr) Intervenções na rede de sprinklers das lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][spr]])      > [[elisp:(progn (other-window 1)(end-of-line)(insert "(spr) Intervenções na rede de sprinklers das lojas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Intervenções na rede de sprinklers das lojas - Técnico]]
 
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(leit) Leituras/Pequenas reparações do sistema de tratamento de águas - Técnico")(other-window -1)(kill-buffer)(delete-window))][leit]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(leit) Leituras/Pequenas reparações do sistema de tratamento de águas - Técnico")(other-window -1)(kill-buffer)(delete-window))][Leituras/Pequenas reparações do sistema de tratamento de águas - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(leir) Limpeza/Desentupimento de esgotos/ralos/caleiras - Técnico")(other-window -1)(kill-buffer)(delete-window))][leir]])     > [[elisp:(progn (other-window 1)(end-of-line)(insert "(leir) Limpeza/Desentupimento de esgotos/ralos/caleiras - Técnico")(other-window -1)(kill-buffer)(delete-window))][Limpeza/Desentupimento de esgotos/ralos/caleiras - Técnico]]
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "(sos n) Trabalhos diversos na rede de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][sos n]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "(sos n) Trabalhos diversos na rede de incêndios - Técnico")(other-window -1)(kill-buffer)(delete-window))][Trabalhos diversos na rede de incêndios - Técnico]]

--- Sem tipo -------------------------------------------------------------------
 > Não tipificada
 > ([[elisp:(progn (other-window 1)(end-of-line)(insert "Não Tipificada")(other-window -1)(kill-buffer)(delete-window))][nao]])    > [[elisp:(progn (other-window 1)(end-of-line)(insert "Não Tipificada")(other-window -1)(kill-buffer)(delete-window))][Nao Tipificada]]



 
* Instruções

[[elisp:(beginning-of-buffer)][Topo]] da pagina

Fx: dv-print-siigo-ot-type       ;; Print text in another buffer open in another window by clicking the links and closes this one buffer
Fx: <<dv-insert-siigo-ot-type>>  ;; Inser text in current buffer in another line, opening a new window and then closing
Fx: dv-paste-siigo-ot-type       ;; Just past the whole text list of OTs in the current cursor position (uDev)
Fx: C-s                          ;; (CTRL + S) Interactive search called: iSearch
Fx: C-c C-o                      ;; Ctrl-c Ctrl-o Após pesquisar o texto, o texto terá um link associado, esse lik como é um scrip, basta carregar nesta sequencia de teclas de atalho para preceder à inserção de texto
Fx: ser                          ;; uDev: Send to init.el  
Fx: ...s de av...                ;; uDev
Fx: ...as ex...                  ;; uDev

Nota 1: A função: 'M-x dv-add-ot-just-text' tem um link que abre este documento
Nota 2: O texto entre parenteses representa qual a frase mais curta para se usar no motor de busca do site

Fx: udev: criar Fx para cada abreviatura, para ser automaticamente introduzido o texto desse tipo de OT em frente ao cursor

  Usa a função: dv-print-siigo-ot-type no scratch buffer para imprimir as varias abreviaturas para cada topico
                Esta função cola o texto inteiro sobre os tipos de OT, experimenta no scratch-buffer

